### ISSUE TITLE
Cannot get route

### ISSUE THREAD

**Issue by sebleclerc** [hfhbd/routing-compose#152]
I have a BrowserRouter setup but can't get to navigate to a defined route.

```
@Composable
fun RouterComponent() {
  BrowserRouter(initRoute = "/") {
    route("/") {
      Text("ROOT ROOT")
    }

    route("/map") {
      Text("MAP MAP MAP")
    }

    noMatch {
      Text("NO MATCH \uD83D\uDE22")
    }
  }
}
```

When I load my page at url `http://localhost:8081/` I see the root route. But then if I navigate to `http://localhost:8081/map`, I get a `Cannot GET /map` error. Does that sounds a bell?

Thanks for the help 😄 

FYI, I did try and setup as a `HashRouter` and accessing url `http://localhost:8081/#/map` I do get resolved to my map route.

**Comment by rocketraman** [comment]
Is your backend is resolving `/map` to `index.html`?

**Comment by hfhbd** [comment]
Did you config webpack as mentioned in the readme? 

```js
config.devServer = {
  ...config.devServer, // Merge with other devServer settings
  "historyApiFallback": true
};
```

**Comment by sebleclerc** [comment]
Oh right that was it 😅 Didn't see that. Thanks a lot ! And sorry about it
