### ISSUE TITLE
IllegalArgumentException: Route / cannot be empty. Use noMatch instead

### ISSUE THREAD

**Issue by sebleclerc** [hfhbd/routing-compose#186]
Hi! 
I just updated routing-compose from 0.1.9-dev670 to 0.2.3 and I have that `IllegalArgumentException` in the JS console and nothing is rendered in the webpage.

This is my app:
```
@Composable
fun MainApp() {
  Router()
}
```

And the router:
```
@Composable
fun Router() {
  var locale by remember { mutableStateOf(Locale.FRENCH) }

  BrowserRouter(initPath = "/") {
    route("/") {
      LandingPage(locale)
    }

    route("/map") {
      MapPage(locale)
    }

    noMatch {
      Text("NO MATCH")
    }
  }
}
```

Anything that rings a bell? Not sure what is wrong here 😅 It was working fine with 0.1.9
Thanks!

**Comment by hfhbd** [comment]
Hey, `route("/") {` is not supported at the moment, but I don't remember why. I will take a look.

**Comment by sebleclerc** [comment]
Thanks... and thanks! 😄 

I'm hitting refresh on the maven site for 0.2.4 version be available 😅

**Comment by hfhbd** [comment]
It is already available :D https://repo.maven.apache.org/maven2/app/softwork/routing-compose/
The search could take up to 1-2h, but uploading takes only 10-15 minutes.

**Comment by sebleclerc** [comment]
Yeah! 🥳 When I first updated my gradle file it was maybe 10 min after the merge 🙃 so it wasn't available!
Thanks again!
