### ISSUE TITLE
Update to latest Compose builds.

### ISSUE THREAD

**Issue by Ayfri** [hfhbd/routing-compose#197]
Hey, there have been multiple Compose builds released since last release of Routing Compose, and now it supports Kt 1.7.0 and also `js` only projects, it could be great to have this :)

I tested and for now using the 741 as long as Kotlin 1.7.0 doesn't seem to break the library. However, using `kotlin("js")` does.

**Comment by hfhbd** [comment]
Sure, I am just surprise why my playground app did work. Do you use a js only project? Maybe it depends on the KGP which is used in root gradle and I use `multiplatform` for the full stack app but `js` in the web module.
