### ISSUE TITLE
CompositionLocal LocalDensity not present

### ISSUE THREAD

**Issue by xtexChooser** [hfhbd/routing-compose#204]
When I was using this library in a Web project, I got this error: `CompositionLocal LocalDensity not present`.

Code:
```
@Composable
fun WebRouter() {
    HashRouter("/") {
        route("/") {
            Text("Hello World")
        }
    }
}

fun main() {
    renderComposable(rootElementId = "root") {
        Text("as")
        WebRouter()
    }
}
```

The exception threw in the `Text` in the router, the `Text` outside does not throw any exception.

 Why is it happening? Thanks.

**Comment by xtexChooser** [comment]
When I removed the `WebRouter`, the page rendered correctly.

**Comment by xtexChooser** [comment]
However, when I move it out of the HashRouter, it does not works, too. But, if I call it directly in the `renderComposable`, it works.

The `Text` in 
```
fun main() {
    renderComposableInBody {
        Text("TEST!")
        WebRouter()
    }
}
```
works, but below not:
```
@Composable
fun WebRouter() {
        Text("Test")
    HashRouter().route("/") {
        Routing()
    }
}
```

**Comment by hfhbd** [comment]
Hey, could you provide a reproducer? I tried your first code: 
```kotlin
@Composable
fun WebRouter() {
    HashRouter("/") {
        route("/") {
            Text("Hello World")
        }
    }
}

fun main() {
    renderComposable(rootElementId = "root") {
        Text("as")
        WebRouter()
    }
}
```
and it works fine.
[untitled.zip](https://github.com/hfhbd/routing-compose/files/9098945/untitled.zip)

**Comment by xtexChooser** [comment]
Yeah, I will later. Thanks.

**Comment by xtexChooser** [comment]
@hfhbd I found the problem! It is caused by the Material 3.

This problem causes when using `androidx.compose.material3.Text`.

Add
```kotlin
@OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
api(compose.material3)
```
then import androidx.compose.material3.Text. I think this is a problem of compose.

**Comment by hfhbd** [comment]
Okay, so it is reproducible without routing? Otherwise could you still upload your reproducer to analyze the integration with routing?

**Comment by xtexChooser** [comment]
emmm good problem, testing

**Comment by xtexChooser** [comment]
Ok, I tested. It is JetBrains' job. `androidx.compose.material3.Text` does not work even without routing.

Really thanks.

**Comment by xtexChooser** [comment]
Moved to JetBrains/compose-jb#2186.
