### ISSUE TITLE
Add implementation variants 

### ISSUE THREAD

**Issue by ixiDev** [hfhbd/routing-compose#226]
Hi.
Thanks for this work.

I have a problem adding this library to the desktop app, when I add `implementation("app.softwork:routing-compose:LATEST")`

It requires web dependencies, for my project it's only a desktop app. I think it's helpful to add implementation variants by platform (web, desktop....)

**Comment by hfhbd** [comment]
Please add a reproducer. routing-compose works with JVM only targets: 
[untitled3.zip](https://github.com/hfhbd/routing-compose/files/9389945/untitled3.zip)

**Comment by ixiDev** [comment]
Ok I will test it and get back to you
