### ISSUE TITLE
New library that integrates routine-compose.

### ISSUE THREAD

**Issue by beyondeye** [hfhbd/routing-compose#234]
Hi I am developing a [library ](https://github.com/beyondeye/compose_bloc) for compose multiplatform that incorporates also some modules for navigation. I have recently added support for path-based navigation: I have incorporated a modified version of routing-compose: instead of integrating the router with the composition, I have separated it completely. [Here you can see](https://beyondeye.gitbook.io/compose-bloc/router-and-path-based-navigation) the documentation for the library. Is it ok the way I have cited the original code from routine-compose. Do you want me to add something else?

**Comment by hfhbd** [comment]
Hey, sure linking and citing is absolute okay. 
Although I don't mind and I am not a laywer, I would add the license (Apache-2.0) to the link too: `//original code from https://github.com/hfhbd/routing-compose (Apache-2.0)` just for good style.

I am just curious why do you need to adopt the code :) What about a new Router implementation or using delegation instead?

**Comment by hfhbd** [comment]
Yeah, I split the routing from composition in the past too, but the design was annoying: you can't apply composable everywhere and lacks dynamic changing the routing tree during runtime. https://github.com/hfhbd/routing-compose/blob/0880334dbdb332e3c55960bc62ea5940f6d6acec/src/jsTest/kotlin/app/softwork/routingcompose/IntegerRoutingTest.kt#L39

**Comment by beyondeye** [comment]
I understand. I prefer clearer boundaries between UI rendering (call to composable functions),   app logic (dynamic routing) and routing (static routing) for several reasons. But I understand what you are saying
