### ISSUE TITLE
[Question] Does this support Compose Web?

### ISSUE THREAD

**Issue by MohamedRejeb** [hfhbd/routing-compose#330]
Hi,
I'm looking for a routing library for compose web, I think that you need to change compose web with compose html in `Readme.md` and the repo description because it's confusing.

I want to know if it's possible to use this library with compose web (canvas)

Thanks.

**Comment by Daio-io** [comment]
@MohamedRejeb Here is a sample using it with Compose Web Canvas

https://github.com/Daio-io/wasm-canvas-routing-sample

**Comment by hfhbd** [comment]
Both, the routing is independent of the used UI. I will update the readme.
