### ISSUE TITLE
Support Compose 1.6.0-beta01

### ISSUE THREAD

**Issue by Queatz** [hfhbd/routing-compose#342]
I recently updated my entire project to Kotlin `1.9.22` and Compose `1.6.0-beta01`. Now when I run my web target I get the following in the browser console:

message: "Function 'BrowserRouter' can not be called: No function found for symbol 'app.softwork.routingcompose/BrowserRouter|BrowserRouter(kotlin.String;kotlin.Function3<app.softwork.routingcompose.RouteBuilder,androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int){}[0]'"
​
name: "IrLinkageError"
​
stack: "captureStack@webpack-internal:///./kotlin/kotlin-kotlin-stdlib.js:4400:25\nIrLinkageError@webpack-internal:///./kotlin/kotlin-kotlin-stdlib.js:5722:17\nthrowLinkageError@webpack-internal:///./kotlin/kotlin-kotlin-stdlib.js:5718:11\nComposableSingletons$MainKt$lambda_2$lambda$lambda_8o4o75_0/<@webpack-internal:///./kotlin/ailaai.js:4969:26\n@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:33853:92\nComposableLambda$invoke$ref_3/<@webpack-internal:///./kotlin/ailaai.js:4979:25\nCompositionLocalProvider@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:7229:12\nComposableSingletons$MainKt$lambda_2$lambda_dts8wk@webpack-internal:///./kotlin/ailaai.js:4305:29\n@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:33867:92\nComposableLambda$invoke$ref_0/<@webpack-internal:///./kotlin/ailaai.js:4197:25\nrenderComposable$lambda/<@webpack-internal:///./kotlin/html-internal-html-core-runtime.js:418:17\n@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:33853:92\nComposableLambda$invoke$ref/<@webpack-internal:///./kotlin/html-internal-html-core-runtime.js:407:25\ninvokeComposable@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:34274:15\ndoCompose@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:2297:31\n@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:3624:14\n@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:6281:27\n@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:11630:27\ncomposeInitial@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:4883:20\n@webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:6199:19\nrenderComposable@webpack-internal:///./kotlin/html-internal-html-core-runtime.js:336:17\nrenderComposableInBody@webpack-internal:///./kotlin/html-internal-html-core-runtime.js:324:12\nmain@webpack-internal:///./kotlin/ailaai.js:4082:27\n@webpack-internal:///./kotlin/ailaai.js:89957:3\n@webpack-internal:///./kotlin/ailaai.js:5:35\n@webpack-internal:///./kotlin/ailaai.js:8:2\n./kotlin/ailaai.js@http://localhost:4040/ailaai.js:9895:1\n__webpack_require__@http://localhost:4040/ailaai.js:10527:33\n@http://localhost:4040/ailaai.js:11602:56\n@http://localhost:4040/ailaai.js:11605:12\nwebpackUniversalModuleDefinition@http://localhost:4040/ailaai.js:17:20\n@http://localhost:4040/ailaai.js:18:3\n"
​

**Comment by hfhbd** [comment]
Well, this is somehow expected after a (major) bump of the Compose compiler and the yet unstable klibs. I will create a new 1.5.12 compatible release today, but I guess you need a 1.6.0-dev compatible release too.

**Comment by hfhbd** [comment]
I released `0.2.14-1.6.0-beta01`, will be available on mavenCentral after 1h.
