### ISSUE TITLE
Nested routing issue

### ISSUE THREAD

**Issue by TomislavMladenov** [hfhbd/routing-compose#373]
I love the library and it's simplicity, however I can't make the nested routing work for some reason.

I am using simple routing:

```
BrowserRouter(initPath = "/") {
    route("/") {
        Text("This is default route")
    }
    route("/user") {
         string {
             Text("This is user route with uuid: $it")
          }
     }
     route("/grades") {
         Text("This is grades route")
     }
}
```
                
 The routes with `baseUrl/user` and `baseUrl/grades` are working. If I try something like `baseUrl/user/someRandomId` I see only blank screen. 
 
 Included the `devServcerConfig.js` 
 not sure what is wrong. 

If I use `navigate` function it works. For example: `router.navigate(user/someRandomId)` it works. 
If I try to enter it in the browser it's not working, simply empty page, even the `noMatch` component is not shown. 

The issue would be if the user open a link, scan QR code etc.
 
 Any help would be very appreciated.

**Comment by exaucae** [comment]
Hey @TomislavMladenov, sorry to bother, 
is there any chance you can share your webpack setup? I still didn't get Browser router working ( see #421)
