### ISSUE TITLE
Query parameter support

### ISSUE THREAD

**Issue by mpetuska** [hfhbd/routing-compose#95]
It would be great if the router could support query parameters and ignore them when making routing decisions, yet still expose them when route is matched. This would be great way to build permalinks with some preconfigured state (e.g. search/filter form).

This should work for both, BrowserRouter (`localhost:8080/route?param=true&param2=true`) and HashRouter (`localhost:8080/#/route?param=true&param2=true`)

Aditionally, arrays could be also supported and parsed properly (`localhost:8080/#/route?arrayParam=one&arrayParam=two` should result in value of `"arrayParam" to setOf("one", "two")`)

**Comment by hfhbd** [comment]
Indeed, this feature would be handy, although the different encoding formats would be tricky. 
Maybe Ktor could share its encoding as a separate artifact. 

Also how do you want to consume the parameters? Via `Map<String, String`? Then you have to valide the types by yourself. Alternative a direct mapping to a `data class` would be nice too.

**Comment by hfhbd** [comment]
After talking with the Ktor team, the new Location feature won't be released as a separate artifact, so I implement a simple, untyped version by myself.

**Comment by mpetuska** [comment]
I think `Map<String, List<String>>` is more than enough to start with. This can then be enchanced in the future to support some typesafe DSLs as well.

**Comment by mpetuska** [comment]
BTW, I'm not sure if list is the right way to go. I can't think of a case where you'd want duplicate values in query parameter list. But hey, it might be just me.

**Comment by hfhbd** [comment]
@mpetuska Good question, but I was inspired by Ktor`s query parsing, which uses a `List` too, and you can convert any List to a Set ;)
